module.exports = {
  JA_JP: 'ja-JP',
  EN_US: 'en-US',
  DE_DE: 'de-DE',
  EN_GB: 'en-GB',
  ES_ES: 'es-ES',
  ES_US: 'es-US',
  FR_FR: 'fr-FR',
  HI_IN: 'hi-IN',
  ID_ID: 'id-ID',
  IT_IT: 'it-IT',
  KO_KR: 'ko-KR',
  NL_NL: 'nl-NL',
  PL_PL: 'pl-PL',
  PT_BR: 'pt-BR',
  RU_RU: 'ru-RU',
  ZH_CN: 'zh-CN',
  ZH_HK: 'zh-HK',
  ZH_TW: 'zh-TW',
}
