name: Deploy to Now
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install
      - run: npm install now -g

      - name: "[INFO] Versions"
      - run: |
          cat /etc/os-release
          node --version
          npm --version
          now --version
